version: '3'

services:
  mcp-server:
    build: .
    ports:
      - "3000:3000"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - PORT=3000
    restart: unless-stopped
    volumes:
      - ./logs:/usr/src/app/logs